from random import choice

photos = {
    "diary_thanks": [
        "AgACAgIAAxkBAAN7ZaVAFs9mLMcnvRAygyN0PGI37GQAAl_bMRvCOShJy6_C_0dUDGwBAAMCAAN5AAM0BA",
        "AgACAgIAAxkBAAN8ZaVAFsm9lsHtEhxVJ_Pv7JHNl4IAAmDbMRvCOShJ9xd9-iPxGcwBAAMCAAN5AAM0BA",
        "AgACAgIAAxkBAAN9ZaVAFzvbas4YhJGxP2Gc69mI5Y0AAmHbMRvCOShJeiwo364k30kBAAMCAAN5AAM0BA",
        "AgACAgIAAxkBAAN-ZaVAF9fftvvRKLiIQskRDrD1wWQAAmLbMRvCOShJPDF0A-U4yL8BAAMCAAN5AAM0BA",
    ],
    "diary_joy": [
        "AgACAgIAAxkBAAOAZaVB3IEvpU_tjFzPzXdgs7yx9bUAAmrbMRvCOShJdcCzgRY_vy4BAAMCAAN5AAM0BA",
        "AgACAgIAAxkBAAOBZaVB3CbO7UowOc-WIJM103zB5XYAAmvbMRvCOShJo0BKAvjgKEcBAAMCAAN5AAM0BA",
        "AgACAgIAAxkBAAOCZaVB3N0BOLdjTMk4Wf52rL1gLGEAAmzbMRvCOShJFh9phOvePIEBAAMCAAN5AAM0BA",
        "AgACAgIAAxkBAAODZaVB3IQRTLIOk4eUDvUJAAFQNRE9AAJt2zEbwjkoSSuPsJjD24SkAQADAgADeQADNAQ"
    ],
    "diary_stress": [
        "AgACAgIAAxkBAAOEZaVCbcUBARlHDEcRkirKf-H5IWsAAnPbMRvCOShJ2JDdHoPACHwBAAMCAAN5AAM0BA",
        "AgACAgIAAxkBAAOFZaVCbRwHz_9cf33KYJXOREO2MYoAAnTbMRvCOShJbm0AAQYH_DJZAQADAgADeQADNAQ",
        "AgACAgIAAxkBAAOGZaVCbc24O1VDECZLpLXVVX_ZNzQAAnXbMRvCOShJ9VuLyOjepCQBAAMCAAN5AAM0BA",
        "AgACAgIAAxkBAAOHZaVCbTsFVjNnxon8sQ5xJIbIciQAAnfbMRvCOShJBiKml2_QLy8BAAMCAAN5AAM0BA"
    ],
    "diary_attractions": [
        "AgACAgIAAxkBAAOIZaVDtNgORRTNMLx0-Nieczrj6dQAAn_bMRvCOShJnpONzFjGuxgBAAMCAAN5AAM0BA",
        "AgACAgIAAxkBAAOJZaVDtF6UW4MIzg98fGz3IhKLk1MAAoDbMRvCOShJfhFNxsWRMBQBAAMCAAN5AAM0BA",
        "AgACAgIAAxkBAAOKZaVDtMX4M4JKDTwclTA3k6lxTb0AAoHbMRvCOShJdQW3vd7K9uEBAAMCAAN5AAM0BA"
    ],
    "first_visit": [
        "AgACAgIAAxkBAAIBeWXgh4vkjZL0cQa-337Mk9RJxOKjAAJy2TEbQukJS-JPAinEwU4bAQADAgADeQADNAQ",
        "AgACAgIAAxkBAAIBemXgh6OTkGJg4zadK17Wk-wcI2iIAAJz2TEbQukJS7boVgGjs7J5AQADAgADeQADNAQ",
        "AgACAgIAAxkBAAIBe2Xgh7skljOybe7Byq8NN6izVbvbAAJ02TEbQukJSxa5I7B0nztUAQADAgADeQADNAQ",
        "AgACAgIAAxkBAAIBfGXgh8V8Zm8auI_aKa_EgKYv9HlxAAJ12TEbQukJSwJ1zXt1mREHAQADAgADeQADNAQ"
    ],
    "diary_goals": "AgACAgIAAxkBAAIBd2Xghx-Aqa5A6QTBgOtxOSTQPlnzAAJx2TEbQukJS85sD1-BSi0XAQADAgADeQADNAQ",
    "profile": "AgACAgIAAxkBAAOLZaVEHAHmCuh1BFS1K3R6hxkp5lUAAoLbMRvCOShJWiVeDuhG4e4BAAMCAAN5AAM0BA",
    "notice": "AgACAgIAAxkBAAOMZaVETfmIJm89w4oUg3ZAopWyujAAAoPbMRvCOShJF5dvlfYwEE0BAAMCAAN5AAM0BA",
    "support": "AgACAgIAAxkBAAONZaVEXWcV2Xa7t2EzJ4SbcbrhNy0AAoTbMRvCOShJ7oQDVv5f6JwBAAMCAAN5AAM0BA",
    "subscribe": "AgACAgIAAxkBAAOOZaVEtSPCUztwZ9lOU-q1ln7BHdQAAoXbMRvCOShJR0J5Txr-Tr4BAAMCAAN5AAM0BA",
    "payment": "AgACAgIAAxkBAAMwZW86xv01AAHlm4TUqq9r5UmkT2AHAALu0TEbsPFYS7JKb_ha4LZRAQADAgADeQADMwQ",
    "pay_conf": "AgACAgIAAxkBAAP7Za6PP26uPopXnVYkMJJkt5kIC4IAAsPUMRtfJXlJ3ZavlGo4ewkBAAMCAAN5AAM0BA",
    "start": "AgACAgIAAxkBAAP8Za6PWQiXv2f-o3So2LrhSb4P2q8AAsTUMRtfJXlJ1hNMspx8IOsBAAMCAAN5AAM0BA",
    "choice_card": "AgACAgIAAxkBAAP9Za6PdpcCRiuxi1nfa7luOesLjaQAAsjUMRtfJXlJ6t9s6OJf-fwBAAMCAAN5AAM0BA",
    "default": "AgACAgIAAxkBAAIBcGXduYBqgf_VVUo37EHWmWaQR2egAAKV8jEbU7LwSrn3LYwOZA_SAQADAgADeAADNAQ",
}


# возвращает нужное фото
def get_cover_photo(key: str) -> str:
    value = photos[key]
    if type(value) == list:
        value = choice(value)
    return value
